### PR TITLE
Fetch esbuild.wasm from unpkg

### LINKED ISSUE #156: The landing page components don't seem to work
The hero animation is stopped and the counter example is disabled for now.

image

Browser error here: 

image

Deno Deploy error logs (with my fork): 

image

And error line is here:

image

https://unpkg.com/esbuild-wasm@0.14.34/esm/browser.js

it seems failed to fetch wasm binary.

### PR DESCRIPTION
**Pull request by hashrock**
Closes #156

### CODE REVIEW

File: src/server/bundle.ts [hunk 1]
```diff
@@ -7,7 +7,8 @@ async function ensureEsbuildInialized() {
   if (esbuildInitalized === false) {
     if (Deno.run === undefined) {
       esbuildInitalized = esbuild.initialize({
-        wasmURL: new URL("./esbuild-wasm/esbuild.wasm", import.meta.url).href,
+        wasmURL: new URL("https://unpkg.com/esbuild-wasm@0.14.34/esbuild.wasm")
+          .href,
```
Comment (lucacasonato) [inline src/server/bundle.ts]:
```suggestion
        wasmURL: "https://unpkg.com/esbuild-wasm@0.14.34/esbuild.wasm",
```

**Review by lucacasonato — APPROVED** [review]
Thanks @hashrock!
