### PR TITLE
fix(context): handle HEAD requests

### LINKED ISSUE #1033: fresh ought to respond to HEAD requests
currently it responds with 405

```
% curl -I https://fresh.deno.dev/
HTTP/2 405 
accept: GET
vary: Accept-Encoding
date: Wed, 15 Feb 2023 08:54:06 GMT
via: http/2 edgeproxy-h
server: deno/gcp-asia-northeast1
```

### PR DESCRIPTION
**Pull request by hashrock**
close #1033

### CODE REVIEW

File: tests/main_test.ts [hunk 1]
```diff
@@ -252,6 +252,13 @@ Deno.test("static file - by file path", async () => {
   assertEquals(resp3.status, Status.NotModified);
   assertEquals(resp3.headers.get("etag"), etag);
   assertEquals(resp3.headers.get("content-type"), "text/plain");
+
+  const resp4 = await router(
+    new Request("https://fresh.deno.dev/foo.txt", {
+      method: "HEAD"
+    }),
+  );
+  assertEquals(resp4.status, Status.OK);
```
Comment (ry) [inline tests/main_test.ts]: Probably makes sense to have a new standalone test case for head requests. Also check that the response body is empty.

**Review by kt3k — APPROVED** [review]
LGTM! 👍
