### PR TITLE
fix init

### LINKED ISSUE #60: fresh init is broken
Run Fresh init, then start the server.

```
$ deno run -A --unstable --watch main.ts
Check file:///C:/Users/sylva/Documents/Projects/OpenSource/test_fresh/main.ts
error: TS2345 [ERROR]: Argument of type '{ pages: { "./pages/api/joke.ts": typeof $0; "./pages/index.tsx": typeof $1; "./pages/[name].tsx": typeof $2; }; baseUrl: string; }' is not assignable to parameter of type 'Routes'.
  Types of property 'pages' are incompatible.
    Type '{ "./pages/api/joke.ts": typeof $0; "./pages/index.tsx": typeof $1; "./pages/[name].tsx": typeof $2; }' is not assignable to type 'Record<string, PageModule | RendererModule>'.
      Property '"./pages/api/joke.ts"' is incompatible with index signature.
        Type 'typeof import("file:///C:/Users/sylva/Documents/Projects/OpenSource/test_fresh/pages/api/joke.ts")' is not assignable to type 'PageModule | RendererModule'.
          Type 'typeof import("file:///C:/Users/sylva/Documents/Projects/OpenSource/test_fresh/pages/api/joke.ts")' is not assignable to type 'PageModule'.
            Types of property 'handler' are incompatible.
              Type '(_req: Request) => Response' is not assignable to type 'Handler | Handlers | undefined'.
                Type '(_req: Request) => Response' is not assignable to type 'Handler'.
                  Types of parameters '_req' and 'ctx' are incompatible.
                    Type 'HandlerContext<Record<string, string>>' is missing the following properties from type 'Request': cache, credentials, destination, headers, and 17 more.
await start(routes);
            ~~~~~~
    at file:///C:/Users/sylva/Documents/Projects/OpenSource/test_fresh/main.ts:10:13
Watcher Process finished. Restarting on file change...
```

### PR DESCRIPTION
**Pull request by sylc**
fix https://github.com/lucacasonato/fresh/issues/60

### CODE REVIEW

File: src/cli/init.ts [hunk 1]
```diff
@@ -113,8 +113,10 @@ export default function Greet(props: Props) {
     join(directory, "pages", "[name].tsx"),
     PAGES_GREET_TSX,
   );
+  const serverUrl = new URL("../../server.ts", import.meta.url);
   const PAGES_API_JOKE_TS =
-    `// Jokes courtesy of https://punsandoneliners.com/randomness/programmer-jokes/
+    `import { HandlerContext } from "${serverUrl}";
+    // Jokes courtesy of https://punsandoneliners.com/randomness/programmer-jokes/
```
Comment (lucacasonato) [inline src/cli/init.ts]:
```suggestion
// Jokes courtesy of https://punsandoneliners.com/randomness/programmer-jokes/
```

**Review by lucacasonato — APPROVED** [review]
Thanks @sylc!
