### PR TITLE
fix: The "Made with Fresh" Badge broke

### LINKED ISSUE #969: The "Made with Fresh" Badge broke
image

> The resource at “https://fresh.deno.dev/fresh-badge.svg” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)#

Everywhere. For example: https://merch.deno.com/ and https://showcase-chat.deno.dev/

### PR DESCRIPTION
**Pull request by hashrock**
Close #969

I added a CORS header when I added the ga4 middleware, but this applied to the `static/` files as well, and it causes "Made with Fresh" badge broke.

It may be desirable to remove the CORS header from `static/` files only, but for the time being, I have revert the addition of headers including CORS.

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM 👍 

> It may be desirable to remove the CORS header from static/ files only

Let's figure out this later

File: www/main_test.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  for await (const line of lines) {
+    if (line.includes("Listening on http://")) {
+      started = true;
+      break;
+    }
+  }
+  if (!started) {
+    throw new Error("Server didn't start up");
+  }
+  await delay(100);
```
Comment (kt3k) [inline www/main_test.ts]: nit: this delay seems unnecessary?

Comment (hashrock) [reply www/main_test.ts]: yeah you are right!
