### PR TITLE
fix: hide `node_modules` and `vendor` from update output

### LINKED ISSUE #3082: bug: `@fresh/update` processes `node_modules` folder
Discovered when upgrading the JSR codebase.

```
asher@Ashers-MacBook-Air frontend % deno run -Ar jsr:@fresh/update@2.0.0-alpha.37 .
 🍋 Fresh Updater 

Note: Breaking changes may require additional manual updates.

🚀 Starting Fresh 1 to Fresh 2 migration...
📝 Updating configuration files...
✅ Configuration updated successfully
🔍 Scanning for source files...
📁 Found 2255 files to process
🔄 Processing files...
[00:47] [##################################################] [2255/2255 files]

📊 Migration Summary:
   Total files processed: 2255
   Successfully modified: 11
   Unmodified (no changes needed): 2244

📝 Modified Files:
   ✓ node_modules/@preact/signals/dist/signals.d.ts
   ✓ node_modules/preact/compat/src/index.js
   ✓ node_modules/preact/compat/src/suspense.js
   ✓ node_modules/preact/devtools/dist/devtools.module.js
   ✓ node_modules/preact/devtools/src/devtools.js
   ✓ node_modules/preact/compat/dist/compat.module.js
   ✓ node_modules/preact/jsx-runtime/dist/jsxRuntime.module.js
   ✓ node_modules/preact/jsx-runtime/src/index.js
   ✓ node_modules/preact/debug/dist/debug.module.js
   ✓ node_modules/preact/debug/src/component-stack.js
   ✓ node_modules/preact/src/jsx.d.ts

🎉 Migration completed successfully!
```

### PR DESCRIPTION
**Pull request by SisyphusZheng**
Added logic to filter out files in node_modules and vendor directories from user-facing logs and migration summaries in the update process. Updated tests to verify that these files are processed but not shown in logs.

close #3082

### CODE REVIEW

File: update/src/update_test.ts [hunk 1]
```diff
@@ -365,9 +366,10 @@ Deno.test(
   },
 );
 
-Deno.test.ignore(
-  "update - 1.x update handler signature variable",
-  async () => {
+Deno.test({
+  ignore: true,
+  name: "update - 1.x update handler signature variable",
+  fn: async () => {
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: This seems like an unrelated change. Can you revert it?

File: update/src/update_test.ts [hunk 2]
```diff
@@ -398,11 +400,12 @@ Deno.test.ignore(
...
-);
+});
 
-Deno.test(
-  "update - 1.x update handler signature non-inferred",
-  async () => {
+Deno.test({
+  ignore: true,
+  name: "update - 1.x update handler signature non-inferred",
+  fn: async () => {
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: This seems like an unrelated change. Can you revert it?

File: update/src/update_test.ts [hunk 3]
```diff
@@ -426,11 +429,12 @@ export const handler = {
...
-);
+});
 
-Deno.test(
-  "update - 1.x update handler signature with destructure",
-  async () => {
+Deno.test({
+  ignore: true,
+  name: "update - 1.x update handler signature with destructure",
+  fn: async () => {
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: Unrelated, please revert

File: update/src/update_test.ts [hunk 4]
```diff
@@ -557,9 +561,10 @@ export default async function Index(ctx: FreshContext) {
   },
 );
 
-Deno.test.ignore(
-  "update - 1.x ctx.renderNotFound() -> ctx.throw()",
-  async () => {
+Deno.test({
+  ignore: true,
+  name: "update - 1.x ctx.renderNotFound() -> ctx.throw()",
+  fn: async () => {
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: unrelated

File: update/src/update_test.ts [hunk 5]
```diff
@@ -593,11 +598,12 @@ export const handler: Handlers = {
...
-);
+});
 
-Deno.test.ignore(
-  "update - 1.x ctx.remoteAddr -> ctx.info.remoteAddr",
-  async () => {
+Deno.test({
+  ignore: true,
+  name: "update - 1.x ctx.remoteAddr -> ctx.info.remoteAddr",
+  fn: async () => {
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: unrelated

File: update/src/update_test.ts [hunk 6]
```diff
@@ -627,14 +633,17 @@ export const handler: Handlers = {
...
-    "/routes/index.tsx": `import { Handlers } from "$fresh/server.ts";
+Deno.test({
+  ignore: true,
+  name: "update - 1.x destructured ctx members",
+  fn: async () => {
+    await using _tmp = await withTmpDir();
+    const dir = _tmp.dir;
+    await writeFiles(dir, {
+      "/deno.json": `{}`,
+      "/routes/index.tsx": `import { Handlers } from "$fresh/server.ts";
```
Comment (marvinhagemeister) [inline update/src/update_test.ts]: unrelated

File: update/src/update.ts [hunk 7]
```diff
@@ -10,6 +10,13 @@ export const FRESH_VERSION = "2.0.0-alpha.37";
 export const PREACT_VERSION = "10.26.9";
 export const PREACT_SIGNALS_VERSION = "2.2.1";
 
+// Function to filter out node_modules and vendor directories from logs
+function shouldHideFromLogs(filePath: string): boolean {
+  const normalizedPath = filePath.replace(/\\/g, "/");
+  return normalizedPath.includes("/node_modules/") ||
+    normalizedPath.includes("/vendor/");
+}
+
```
Comment (marvinhagemeister) [inline update/src/update.ts]: This can be simplified to:

```suggestion
const HIDE_FILES = /[\\/]+(node_modules|vendor)[\\/]+/;
```
And then later do `!HIDE_FILES.test(someFilePath)`.

Comment (SisyphusZheng) [reply update/src/update.ts]: cool, thx

File: update/src/update_test.ts (hunk 1 above)
Comment (SisyphusZheng) [reply update/src/update_test.ts]: To be honest, this issue was a format error I encountered when I cloned and ran deno test, but it seems to be fine now. Sorry for the trouble.

**Review by marvinhagemeister — APPROVED** [review]
Sweet, thanks!
