### PR TITLE
fix: ensure file paths in snapshot.json uses /

### LINKED ISSUE #2703: [Fresh-v2] Building assets with subfolders fails on windows
When building Fresh v2 on Windows, using subfolders for `assets` seems to break when running the app in production after building. The reason seems to be inconsistent paths with `\\`:

```json
  "staticFiles": {
    "/images\\logo.svg": {
      "hash": "1e0b7aa79648883158742ec4f064980898c4c8feff0c3300b8c7ea4485ef1354",
      "generated": false
    },
```

Trying to fetch `/images/logo.svg` just gives a HTTP 404 error.

## Reproduction

1. Initialize a Fresh project
    ```bash
    deno run -Ar jsr:@fresh/init@2.0.0-alpha.22
    ```
2. Move the `assets/logo.svg` to `assets/images/svg.logo`
3. Update `routes/index.tsx` with updated image path
4. Build Fresh with `deno task build`
5. Start prod server with `deno task start`
6. Link to image is broken

### PR DESCRIPTION
**Pull request by csvn**
Avoids `\\\\` paths ending up in `snapshot.json` when using `deno task build` on Windows. Backslashes do not which pathnames in URLs, so these assets are not returned.

Closes #2703

### CODE REVIEW

File: src/dev/dev_build_cache.ts [hunk 1]
```diff
@@ -174,7 +175,7 @@ export class DiskBuildCache implements DevBuildCache {
 
   addUnprocessedFile(pathname: string): void {
     this.#unprocessedFiles.set(
-      pathname,
+      pathname.replaceAll(WINDOWS_SEPARATOR, "/"),
```
Comment (csvn) [inline src/dev/dev_build_cache.ts:178]: I don't know if there is a "better" way to normalize file system paths to URL-like paths. This seems to work at least, since manually replacing `\\` with `/` in my `snapshot.json` locally fixes the issue.

**Comment by csvn** [comment]
I think perhaps the `.addProcessedFile()` will produce the same error, but I only fixed this for the "Un"-processed files.

**Review by marvinhagemeister — APPROVED** [review]
Sweet, great catch! Love that you added a test as well!

File: src/dev/dev_build_cache.ts (hunk 1 above)
Comment (marvinhagemeister) [reply src/dev/dev_build_cache.ts:178]: Seems fine to me.
