### PR TITLE
fix: parse multiple route params in same part

### LINKED ISSUE #1516: Not found route with extension in the file name
The following file:

```
routes/catalog/movie/[id].json.ts
```

Will not match the path "/catalog/movie/foo.json".

I traced it down to [this branch](https://github.com/denoland/fresh/blob/e18a60851503b4b24956fbf889338a4db7d6f3d5/src/server/context.ts#L1014-L1016), and it won't replace `[id].json` with `:id.json`

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Our existing way to parse file paths to patterns for routes was a bit rudimentary. It only allowed parameters to be the full path segments:

Before:

- `foo/[bar]@foo` -> `foo/[bar]@foo`

After:

- `foo/[bar]@foo` -> `foo/:bar@foo`

Fixes #1516

### CODE REVIEW

File: src/server/context.ts [hunk 1]
```diff
@@ -1001,20 +1001,47 @@ function getPriority(part: string) {
...
+      for (let i = 0; i < part.length; i++) {
+        const char = part[i];
+        if (char === "[") {
+          // Disallow neighbouring params like `/[id][bar].tsx` because
+          // it's ambigious where the `id` param ends and `bar` begins.
+          if (i > 0 && part[i - 1] === "]") {
+            throw new SyntaxError(
+              `Invalid route pattern: "${path}". A parameter cannot be followed by another parameter without any charactes in between.`,
+            );
+          }
```
Comment (iuioiua) [inline src/server/context.ts]: This case can be caught earlier in the callback function via `if (part.includes("][") ...`

Comment (marvinhagemeister) [reply src/server/context.ts]: updated the PR.

Comment (marvinhagemeister) [reply src/server/context.ts]: updated the PR.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Review by iuioiua — APPROVED** [review]
